definitions:
  model.AddSysAdminDto:
    properties:
      email:
        description: 邮箱
        type: string
      nickname:
        description: 昵称
        type: string
      note:
        description: 备注
        type: string
      password:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
      roleId:
        description: 角色id
        type: integer
      sex:
        description: '性别: 1->男,2->女'
        type: integer
      status:
        description: '状态: 1->启用,2->禁用'
        type: integer
      username:
        description: 用户名
        type: string
    required:
    - email
    - nickname
    - password
    - phone
    - roleId
    - status
    - username
    type: object
  model.AddSysMenuDto:
    properties:
      icon:
        description: 菜单图标
        type: string
      menuName:
        description: 菜单名称
        type: string
      menuStatus:
        description: 启用状态：1->启用；2->禁用
        type: integer
      menuType:
        description: 菜单类型：1->目录；2->菜单；3->按钮
        type: integer
      parentId:
        description: 父菜单id
        type: integer
      sort:
        description: 排序
        type: integer
      url:
        description: 菜单url
        type: string
      value:
        description: 权限值
        type: string
    type: object
  model.AddSysRoleDto:
    properties:
      description:
        description: 描述
        type: string
      roleKey:
        description: 权限字符串
        type: string
      roleName:
        description: 角色名称
        type: string
      status:
        description: '账号启用状态: 1->启用,2->禁用'
        type: integer
    type: object
  model.LoginDto:
    properties:
      password:
        description: 用户密码
        type: string
      username:
        description: 用户账号
        type: string
    type: object
  model.ResetSysAdminPasswordDto:
    properties:
      id:
        description: ID
        type: integer
      password:
        description: 密码
        type: string
    type: object
  model.RoleMenuDto:
    properties:
      id:
        description: ID
        type: integer
      menu_ids:
        description: 菜单id列表
        items:
          type: integer
        type: array
    required:
    - id
    - menu_ids
    type: object
  model.SysAdminIdDto:
    properties:
      id:
        description: ID
        type: integer
    type: object
  model.SysMenuIdDto:
    properties:
      id:
        description: ID
        type: integer
    type: object
  model.SysRoleIdDto:
    properties:
      id:
        description: ID
        type: integer
    type: object
  model.UpdateSysAdminDto:
    properties:
      email:
        description: 邮箱
        type: string
      id:
        description: ID
        type: integer
      nickname:
        description: 昵称
        type: string
      note:
        description: 备注
        type: string
      phone:
        description: 手机号
        type: string
      roleId:
        description: 角色id
        type: integer
      sex:
        description: '性别: 1->男,2->女'
        type: integer
      status:
        description: '状态: 1->启用,2->禁用'
        type: integer
      username:
        description: 用户名
        type: string
    required:
    - email
    - nickname
    - phone
    - roleId
    - status
    - username
    type: object
  model.UpdateSysAdminStatusDto:
    properties:
      id:
        description: ID
        type: integer
      status:
        description: '账号启用状态: 1->启用,2->禁用'
        type: integer
    type: object
  model.UpdateSysMenuDto:
    properties:
      icon:
        description: 菜单图标
        type: string
      id:
        description: ID
        type: integer
      menuName:
        description: 菜单名称
        type: string
      menuStatus:
        description: 启用状态：1->启用；2->禁用
        type: integer
      menuType:
        description: 菜单类型：1->目录；2->菜单；3->按钮
        type: integer
      parentId:
        description: 父菜单id
        type: integer
      sort:
        description: 排序
        type: integer
      url:
        description: 菜单url
        type: string
      value:
        description: 权限值
        type: string
    type: object
  model.UpdateSysRoleDto:
    properties:
      description:
        description: 描述
        type: string
      id:
        description: ID
        type: integer
      roleKey:
        description: 权限字符串
        type: string
      roleName:
        description: 角色名称
        type: string
      status:
        description: '账号启用状态: 1->启用,2->禁用'
        type: integer
    type: object
  model.UpdateSysRoleStatusDto:
    properties:
      id:
        description: ID
        type: integer
      status:
        description: '账号启用状态: 1->启用,2->禁用'
        type: integer
    type: object
  result.Result:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 返回数据
      message:
        description: 提示信息
        type: string
    type: object
info:
  contact: {}
  description: 博客运营后台API接口文档
  title: 博客运营后台
  version: "1.0"
paths:
  /api/failed:
    get:
      description: 失败测试接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 失败测试接口
      tags:
      - 测试相关接口
  /api/success:
    get:
      description: 成功测试接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 成功测试接口
      tags:
      - 测试相关接口
  /api/sysAdmin/add:
    post:
      description: 新增用户
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.AddSysAdminDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 新增用户
      tags:
      - 用户相关接口
  /api/sysAdmin/delete:
    delete:
      description: 根据ID删除用户
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.SysAdminIdDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据ID删除用户
      tags:
      - 用户相关接口
  /api/sysAdmin/info:
    get:
      description: 根据id查询用户
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据id查询用户
      tags:
      - 用户相关接口
  /api/sysAdmin/list:
    get:
      description: 分页查询用户列表
      parameters:
      - description: 分页数
        in: query
        name: pageNum
        type: integer
      - description: 每页数
        in: query
        name: pageSize
        type: integer
      - description: 用户名称
        in: query
        name: username
        type: string
      - description: '账号启用状态: 1->启用,2->禁用'
        in: query
        name: status
        type: string
      - description: 开始时间
        in: query
        name: beginTime
        type: string
      - description: 结束时间
        in: query
        name: endTime
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 分页查询用户列表
      tags:
      - 用户相关接口
  /api/sysAdmin/login:
    post:
      description: 登录
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 登录
      tags:
      - 用户相关接口
  /api/sysAdmin/update:
    put:
      description: 修改用户
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UpdateSysAdminDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 修改用户
      tags:
      - 用户相关接口
  /api/sysAdmin/updatePassword:
    put:
      description: 重置密码
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.ResetSysAdminPasswordDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 重置密码
      tags:
      - 用户相关接口
  /api/sysAdmin/updateStatus:
    put:
      description: 设置用户状态
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UpdateSysAdminStatusDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 设置用户状态
      tags:
      - 用户相关接口
  /api/sysMenu/add:
    post:
      description: 新增菜单
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.AddSysMenuDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 新增菜单
      tags:
      - 菜单相关接口
  /api/sysMenu/delete:
    delete:
      description: 根据ID删除菜单
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.SysMenuIdDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据ID删除菜单
      tags:
      - 菜单相关接口
  /api/sysMenu/info:
    get:
      description: 根据id查询菜单
      parameters:
      - description: 菜单id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据id查询菜单
      tags:
      - 菜单相关接口
  /api/sysMenu/list:
    get:
      description: 查询菜单列表
      parameters:
      - description: 菜单名称
        in: query
        name: menuName
        type: string
      - description: 菜单状态
        in: query
        name: menuStatus
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 查询菜单列表
      tags:
      - 菜单相关接口
  /api/sysMenu/update:
    put:
      description: 修改菜单
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UpdateSysMenuDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 修改菜单
      tags:
      - 菜单相关接口
  /api/sysRole/add:
    post:
      description: 新增角色
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.AddSysRoleDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 新增角色
      tags:
      - 角色相关接口
  /api/sysRole/assignPermissions:
    put:
      description: 分配权限
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.RoleMenuDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 分配权限
      tags:
      - 角色相关接口
  /api/sysRole/delete:
    delete:
      description: 根据ID删除角色
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.SysRoleIdDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据ID删除角色
      tags:
      - 角色相关接口
  /api/sysRole/info:
    get:
      description: 根据id查询角色
      parameters:
      - description: 角色id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据id查询角色
      tags:
      - 角色相关接口
  /api/sysRole/list:
    get:
      description: 分页查询角色列表
      parameters:
      - description: 分页数
        in: query
        name: pageNum
        type: integer
      - description: 每页数
        in: query
        name: pageSize
        type: integer
      - description: 角色名称
        in: query
        name: roleName
        type: string
      - description: '账号启用状态: 1->启用,2->禁用'
        in: query
        name: status
        type: string
      - description: 开始时间
        in: query
        name: beginTime
        type: string
      - description: 结束时间
        in: query
        name: endTime
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 分页查询角色列表
      tags:
      - 角色相关接口
  /api/sysRole/update:
    put:
      description: 修改角色
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UpdateSysRoleDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 修改角色
      tags:
      - 角色相关接口
  /api/sysRole/updateStatus:
    put:
      description: 设置角色状态
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UpdateSysRoleStatusDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 设置角色状态
      tags:
      - 角色相关接口
  /api/sysRole/vo/idList:
    get:
      description: 根据角色id查询菜单数据
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据角色id查询菜单数据
      tags:
      - 角色相关接口
  /api/sysRole/vo/list:
    get:
      description: 查询角色下拉列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 查询角色下拉列表
      tags:
      - 角色相关接口
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
